import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Join Us",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="flex h-full">{children}</main>;
}
